config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :charges, only: [ :new, :create ]
  resources :trips, only: [ :create, :show, :index, :update, :destroy ]
  resources :countries, only: [ :show, :index ] do
    collection do
      get :result
    end
  end

  # for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_desktop_footer.html.erb
<div class="content-desktop">
  <div class="footer">
    <!-- <div class="d-flex justify-content-around align-items-center"> -->

      <!-- icons with links to Github, Linkedin and Facebook -->
      <div class="footer-icons">
        <a class="footer-link mr-1" href="https://github.com/flott2410/falcony" target="_blank"><i class="fab fa-github"></i></a>
        <!-- <a class="footer-link" href="#" target="_blank"><i class="fab fa-linkedin"></i></a> -->
        <!-- <a class="footer-link mr-1" href="/" target="_blank"><i class="fab fa-facebook"></i></a> -->
        <a class="footer-link" href="mailto: contact@falcony.info" target="_blank"><i class="fas fa-at"></i></a>
      </div>

      <!-- links to about Falcony page and Privacy policy -->
      <div class="d-flex justify-content-center footer-link">
        <p class="paragraph-no-margin mr-4"> <%= link_to t("global.navbar.about"), about_path %></p>
        <!-- <p class="paragraph-no-margin mr-0"> <%= link_to t("global.navbar.privacy_policy"), root_path %></p> -->
        <!-- <p class="paragraph-no-margin"> <%= link_to t("global.navbar.cookie_policy"), root_path %></p> -->
      </div>

      <!-- Stripe -->
      <div>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="pk_test_51HP7jHFjvBKJvhpwIhnOBljbfSMBvI0pXddRVQC6SG42JZikYX4xl2X6TbKE72BDGhjJkUQsxV2nLX1RztaLxFjb00X5HXG5bq"
            data-description="Hot Coffee!"
            data-label="Hot Coffee ☕️"
            data-amount="200"
            data-currency="eur"
            data-locale="auto"></script>
      </div>

      <!--  contact info - copyright -->
      <div class="footer-copyright">
         <p class="paragraph-no-margin">Coded with <i class="fas fa-heart"></i> in Lisbon, Milan & Diamante</p>
         <!-- <p class="paragraph-no-margin">Contact us: <a class="footer-link" href = "mailto: contact@falcony.info">contact@falcony.info</a></p> -->
      </div>

    <!-- </div> -->
  </div>
</div>

app/views/shared/_desktop_navbar.html.erb
<div class="content-desktop">
  <div class="navbar navbar-expand-lg navbar-light navbar-lewagon border-navbar">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo/small_logo.svg", class: "logo_navbar my-1 ml-2" %>
    <% end %>

    <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse mr-2" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>

          <li class="nav-item active">
            <%= link_to "Countries", countries_path, class: "nav-link mr-2" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Trips", trips_path, class: "nav-link mr-3" %>
          </li>
<!--           <li class="nav-item active">
            <%= link_to "Notifications", notifications_path, class: "nav-link mr-3" %>
          </li> -->

          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag ('https://res.cloudinary.com/dybiixki8/image/upload/v1600063129/falcony/default_avatar_hlklvm.png'), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to "Countries", countries_path, class: "nav-link mr-2" %>
        </li>

        <li class="nav-item active">
          <!-- I'm not able to make it black instead of gray -->
          <a class="btn btn-default btn-rounded" data-toggle="modal" data-target="#modalLoginForm">Login</a>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_login_modal.html.erb
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email,
                       required: false,
                       autofocus: true,
                       input_html: { autocomplete: "email" } %>
           <%= f.input :password,
                       required: false,
                       input_html: { autocomplete: "current-password" } %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>

          <a href="/users/password/new">Forgot your password?</a>
          <br>
          <a href="/users/sign_up"><strong>No account yet? Register now!</strong></a>
        <div class="modal-footer d-flex justify-content-center">
          <%= f.button :submit, "Log in", class:"log-in-modal-btn" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mobile_footer.html.erb
<!-- Footer mobile -->
<div class="content-mobile">
  <div style="background-color: #505050;" class="p-2">
    <p style="color: white; text-decoration: none;" class="paragraph-no-margin mb-1"><a class="footer-link" href = "/about">About Falcony</a></p>
    <p style="color: white;" class="paragraph-no-margin mb-1">Contact us: <a class="footer-link" href = "mailto: contact@falcony.info">contact@falcony.info</a></p>
    <p style="color: white;" class="paragraph-no-margin mb-1">Coded with <i class="fas fa-heart"></i> in Lisbon, Milan & Diamante</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notification_modal.html.erb
<div class="modal fade" id="modalNotification" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Add Notification</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        Form
      </div>
    </div>
  </div>
</div>

app/views/shared/tests.html.erb
<!-- buttons -->

  <%= link_to "New Button", "#", class: 'btn-falcony' %>

  <br>
  <br>
  <br>

  <!-- cards -->
  <!-- cards -->

  <div class="card-country">
    <div class="">
  	<h2>Country A (Colapsed)</h2>
  	<br>
  	<p>Country description with <strong>relevant info</strong> and links to more info</p>
    </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Falco_peregrinus_good_-_Christopher_Watson.jpg">

    </div>
  </div>

  <br>
  <br>
  <br>
  <div class="card-country" id="expanded">
    <div class="">
  	<h2>Country A (Expanded)</h2>
  	<br>
  	<p>Country description with <strong>relevant info</strong> and links to more info</p>
  	<p>Can I travel here?</p>
  	<p>Do I need tests?</p>
  	<p>Do I need masks in public?</p>
  	<p>Do I need to commit?</p>
  	<p>Can I push to master?</p>
  	<p>--------------</p>
  	<p>--------------</p>

  	<p>--------------</p>
  	<p>--------------</p>
    </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Falco_peregrinus_good_-_Christopher_Watson.jpg">

    </div>
  </div>