config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :charges, only: [ :new, :create ]
  resources :trips, only: [ :create, :show, :index, :update, :destroy ]
  resources :countries, only: [ :show, :index ] do
    collection do
      get :result
    end
  end

  # for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/about.html.erb
<!-- HEADER only for Mobile -->

<div class="content-mobile">

  <!-- Logo and login button -->
  <div class="logo-and-signin-mobile">
    <div class="d-flex justify-content-between">
      <div>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "logo/small_logo_white.svg", class: "logo_navbar_mobile" %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag ('https://res.cloudinary.com/dybiixki8/image/upload/v1600063129/falcony/default_avatar_hlklvm.png'), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% else %>
        <div>
          <a class="btn btn-default btn-rounded" data-toggle="modal" data-target="#modalLoginForm">Login</a>
        </div>
      <% end %>
    </div>
  </div>

</div>


<div class="banner">
  <img src="<%= image_path "about_page/banner-safe.jpg"%>" alt="" class="about-banner">
</div>

<div class="about-container">
  <h4 class="mt-5">About us</h4>
  <hr style="height:2px;width:20%;text-align:left;margin-left:0;border-width:0;background-color:#035C93;">
  <div class="d-flex">
    <div class="vision-text pt-3 pb-5">
    We are young international team from different countries in Europe that all love to travel. As the COVID sitation and rules from the different countries are changing so frequently we had to build a tool that helps to easily get an overview and let's you safe trips and receive notifications for sudden changes. Our mission is to provide easy-to-read but exhaustive information to allow safe travel decisions in the EU in times of COVID-19.
    </div>
    <div>
      <img src="<%= image_path "about_page/team.jpg"%>" alt="Team picture" class="image-about-sources content-desktop">
    </div>
  </div>
</div>

<div class="motivational-quote">
  <h3 class="about-container font-italic">“Not all those who wander are lost” ~ J.R.R. TOLKIEN</h3>
</div>

<div class="about-container">
  <h4 class="mt-5">Our data sources</h4>
  <hr style="height:2px;width:20%;text-align:left;margin-left:0;border-width:0;background-color:#035C93;">
  <div class="d-flex mt-5">
    <div class="vision-text pt-3 pb-5">
    <strong>Travel indications:</strong>
    <br>
    The data is downloaded from Re-Open EU (https://reopen.europa.eu/en). A web platform to support a safe relaunch of travelling and tourism across Europe. It provides real-time information on borders and available means of transport and tourism services in EU Member States.
    </div>
    <div>
      <img src="https://d2v9ipibika81v.cloudfront.net/uploads/sites/21/banner1.jpg" alt="Re-Open EU" class="image-about-sources content-desktop">
    </div>
  </div>
  <div class="d-flex mt-5 mb-5">
    <div class="vision-text pt-3 pb-5">
      <strong>COVID-19 numbers:</strong>
      <br>
      Max Roser, Hannah Ritchie, Esteban Ortiz-Ospina and Joe Hasell (2020) - “Coronavirus Pandemic (COVID-19)". Published online at OurWorldInData.org. Retrieved from: 'https://ourworldindata.org/coronavirus'
    </div>
    <div>
      <img src="https://ourworldindata.org/default-thumbnail.jpg" alt="Our world in data" class="image-about-sources content-desktop">
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Navbar -->
<div class="container-fluid p-0">

  <!-- Section 1: Banner with title, and create trip form -->

    <!-- Desktop -->
    <div class="content-desktop">
      <div>
        <div class="banner-landing-1" style="background-image: linear-gradient(rgba(10, 10, 10, 0.8), rgba(220, 220, 200, 0.1)), url('<%= image_path "landing_page/banner-1.jpg"%>'); ">

          <!-- 3 phrases in home page -->
          <h3 class="mt-3" id="motto">Fly above risk</h3>
          <h3 id="headline-banner-1">Get important and daily updated</h3><br>
          <h3 id="headline-banner-1">Covid-19 related travel info</h3>
          <p id="subheadline-banner-1"><strong>Where do you want to go?</strong></p>

          <!-- search form for creating a trip -->
          <div class="mt-3">
            <%= form_tag result_countries_path, method: :get do %>
              <div class="d-flex justify-content-center" id="home_search">

                <div class="d-flex align-items-center flex-grow mx-3 country_label">
                  <strong id="country_tag">ORIGIN</strong>
                  <div class="mx-3">
                    <%= collection_select(:country, :origin, Country.all, :id, :name, { selected: Country.find_by(name: "Italy").id}, {class: ' min-width-select select2'}) %>
                  </div>
                </div>

                <div class="d-flex align-items-center mx-3 country_label">
                  <div class="mx-3">
                    <%= collection_select(:country, :destination, Country.all, :id, :name, {selected: session[:create_trip_destination_id]}, {class: ' min-width-select select2'}) %>
                  </div>
                <strong id="country_tag">DESTINATION</strong>
                </div>

              </div>

              <div>
                <%= submit_tag "Search", class: "landing-page-button btn btn-falcony mr-5 mt-4" %>
              </div>

            <% end %>
          </div>

        </div>
      </div>
    </div>

    <!-- Mobile -->
    <div class="content-mobile">
      <div class="banner-landing-1-mobile" style="background-image: linear-gradient(rgba(10, 10, 10, 0.8), rgba(220, 220, 200, 0.1)), url('<%= image_path "landing_page/banner-1.jpg"%>'); ">
        <!-- Logo and login button -->
        <div class="d-flex justify-content-between">
          <div>
            <%= link_to root_path, class: "navbar-brand" do %>
              <%= image_tag "logo/small_logo_white.svg", class: "logo_navbar_mobile" %>
            <% end %>
          </div>
          <% if user_signed_in? %>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag ('https://res.cloudinary.com/dybiixki8/image/upload/v1600063129/falcony/default_avatar_hlklvm.png'), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          <% else %>
            <div>
              <a class="btn btn-default btn-rounded" style="color: white;" data-toggle="modal" data-target="#modalLoginForm">Login</a>
            </div>
          <% end %>
        </div>
        <!-- phrase home page -->
        <div class="d-flex flex-column">
          <div class="flex-element-banner-m">
            <br>
            <h3 id="headline-banner-1m">Get important and daily updated Covid-19 related travel info</h3>
            <br>
            <br>
          </div>
          <hr>
          <div class="flex-element-banner-m">
            <p class="banner-text-white"><strong>Where do you want to go?</strong></p>
            <!-- search form for creating a trip -->

            <%= form_tag result_countries_path, method: :get do %>

              <div>
                <p class="banner-text-white">Origin country</p>
                <div>
                  <%= collection_select(:country, :origin, Country.all, :id, :name, { selected: Country.find_by(name: "Italy").id}, {class: 'min-width-select select2'}) %>
                </div>
              </div>

              <div>
                <p class="banner-text-white">Destination country</p>
                <div>
                  <%= collection_select(:country, :destination, Country.all, :id, :name, {selected: session[:create_trip_destination_id]}, {class: 'min-width-select select2'}) %>
                </div>
              </div>

              <div>
                <%= submit_tag "Search", class: "landing-page-button-m btn btn-falcony mt-4" %>
              </div>

            <% end %>
          </div>
          <br>
          <br>
        </div>

      </div>
    </div>

    <!-- Additional link to country index for mobile -->
    <div class="content-mobile" style="background-color: #505050; text-align: center;">
      <br>
      <br>
      <br>
      <h4 style="color: white;">Find details for EU countries:</h4>
      <%= link_to countries_path, class: "nav-link mr-2" do %>
        <i class="fas fa-globe-europe fa-7x"></i>
      <% end %>
      <br>
      <br>
      <br>
    </div>
  <!-- End of Section 1 -->


  <!-- Section 2: First info section explaining falcony -->

    <!-- Desktop -->
    <div class="content-desktop">
      <div class="card-feature">
        <div>
            <img src="https://images.unsplash.com/photo-1593437886622-34881819f1d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1590&q=80" alt="Search">
        </div>
        <div class="description">
        	<h1>Stay informed 🗞</h1>
        	<p>Get all <strong>relevant info</strong> regarding the countries you want to travel to and from</p>
          <p>Can you <strong>take a plane</strong> to go there? Do you need to <strong>quarantine</strong> or a previous negative <strong>test</strong>?</p>
          <p>Check if <strong>restaurants</strong> are open or if you can <strong>go out for a beer</strong> in the night</p>
          <p></p>
        </div>
      </div>
    </div>

    <!-- Mobile -->
    <div class="content-mobile">
      <br>
      <br>
      <br>
      <div style="text-align: center">
        <img class="pics-landing-m" src="https://images.unsplash.com/photo-1593437886622-34881819f1d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1590&q=80" alt="Search">
        <h4 class="mt-3">Stay informed 🗞</h4>
        <p class="mx-3">Get all <strong>relevant info</strong> regarding the countries you want to travel to and from</p>
      </div>
      <br>
      <br>
    </div>

  <!--  End of Section 2 -->


  <!-- Section 3: Second info section about the bookmark and notification feature -->

    <!-- Desktop -->
    <div class="content-desktop">
      <div class="card-feature" id="content-b">
        <div class="description">
            <h1>Dive deep 🕵🏻‍♀️</h1>
            <p>See <strong>detailed</strong> descriptions and <strong>actual Covid numbers</strong> for each country</p>
            <p>Analyze <strong>all the restrictions</strong> in place and how they are changing</p>
            <p>Data <strong>updated everyday</strong> from the European Commission and other official sources</p>
        </div>
        <div>
            <%= image_tag "dive-deep.png" %>
        </div>
      </div>
    </div>

    <!-- Mobile -->
    <div class="content-mobile" style="background-color: #505050;">
      <br>
      <br>
      <br>
      <div style="text-align: center">
        <div class="pics-landing-m"><%= image_tag "dive-deep-m.png" %></div>
        <h4 class="mt-3" style="color: white;">Dive deep 🕵🏻‍♀️</h4>
        <p class="mx-3" style="color: white;">See <strong>detailed</strong> descriptions and <strong>actual Covid numbers</strong> for each country</p>
      </div>
      <br>
      <br>
    </div>

  <!--  End of Section 3 -->


  <!-- Section 4: Third info section with info that Falcony is trustable and maybe references/testimonials -->

    <!-- Desktop -->
    <div class="content-desktop">
      <div class="card-feature" id="content-c">
        <div>
            <img src="https://images.unsplash.com/photo-1590488357944-a71ec5581dfe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1949&q=80" alt="Search">
        </div>
        <div class="description p-1">
          <h1>Live notifications ⚡️</h1>
          <p><strong>Save your preferred routes</strong> to keep them under control</p>
          <p>Receive instant <strong>granular notifications</strong> about bookmarks or choosen countries</p>
          <p><strong>Get an alert</strong> if some values go over the setted limit</p>
        </div>
      </div>
    </div>

    <!-- Mobile -->

    <div class="content-mobile">
      <br>
      <br>
      <br>
      <div style="text-align: center">
        <img class="pics-landing-m" src="https://images.unsplash.com/photo-1590488357944-a71ec5581dfe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1949&q=80" alt="Search">
        <h4 class="mt-3" >Save trips, get alerts ⚡️</h4>
        <p class="mx-3" >Create a profile to <strong>save your preferred routes</strong> and <strong>get notfied</strong> if cases raise over the setted limit</p>
      </div>
      <br>
      <br>
    </div>

  <!--  End of Section 4 -->

</div>